/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Hashtable;

/**
 *
 * @author alexa
 */
public class pointCalcGUI extends javax.swing.JFrame {

    private String global_suit = "Spades";
    private Hand hand;
    
    /**
     * Creates new form pointCalcGUI
     */
    public pointCalcGUI() {
       this.hand = new Hand();
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_addCards = new javax.swing.JPanel();
        b_1 = new javax.swing.JButton();
        b_2 = new javax.swing.JButton();
        b_3 = new javax.swing.JButton();
        b_4 = new javax.swing.JButton();
        b_5 = new javax.swing.JButton();
        b_6 = new javax.swing.JButton();
        b_7 = new javax.swing.JButton();
        b_8 = new javax.swing.JButton();
        b_9 = new javax.swing.JButton();
        b_10 = new javax.swing.JButton();
        b_11 = new javax.swing.JButton();
        b_12 = new javax.swing.JButton();
        b_13 = new javax.swing.JButton();
        slider_suit = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_hand = new javax.swing.JTextArea();
        l_hand = new javax.swing.JLabel();
        l_addCards = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_points = new javax.swing.JTextArea();
        b_calcPoints = new javax.swing.JButton();
        l_points = new javax.swing.JLabel();
        cribT = new javax.swing.JRadioButton();
        cribH = new javax.swing.JRadioButton();
        l_cutCard = new javax.swing.JLabel();
        b_clearHand = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/1S.png"))); // NOI18N
        b_1.setToolTipText("Ace");
        b_1.setPreferredSize(new java.awt.Dimension(67, 100));
        b_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_1ActionPerformed(evt);
            }
        });

        b_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/2S.png"))); // NOI18N
        b_2.setToolTipText("Two");
        b_2.setPreferredSize(new java.awt.Dimension(67, 100));
        b_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_2ActionPerformed(evt);
            }
        });

        b_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/3S.png"))); // NOI18N
        b_3.setToolTipText("Three");
        b_3.setPreferredSize(new java.awt.Dimension(67, 100));
        b_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_3ActionPerformed(evt);
            }
        });

        b_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/4S.png"))); // NOI18N
        b_4.setToolTipText("Four");
        b_4.setPreferredSize(new java.awt.Dimension(67, 100));
        b_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4ActionPerformed(evt);
            }
        });

        b_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/5S.png"))); // NOI18N
        b_5.setToolTipText("Five");
        b_5.setPreferredSize(new java.awt.Dimension(67, 100));
        b_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_5ActionPerformed(evt);
            }
        });

        b_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/6S.png"))); // NOI18N
        b_6.setToolTipText("Six");
        b_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_6ActionPerformed(evt);
            }
        });

        b_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/7S.png"))); // NOI18N
        b_7.setToolTipText("Seven");
        b_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_7ActionPerformed(evt);
            }
        });

        b_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/8S.png"))); // NOI18N
        b_8.setToolTipText("Eight");
        b_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_8ActionPerformed(evt);
            }
        });

        b_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/9S.png"))); // NOI18N
        b_9.setToolTipText("Nine");
        b_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_9ActionPerformed(evt);
            }
        });

        b_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/10S.png"))); // NOI18N
        b_10.setToolTipText("Ten");
        b_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_10ActionPerformed(evt);
            }
        });

        b_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/11S.png"))); // NOI18N
        b_11.setToolTipText("Jack");
        b_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_11ActionPerformed(evt);
            }
        });

        b_12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/12S.png"))); // NOI18N
        b_12.setToolTipText("Queen");
        b_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_12ActionPerformed(evt);
            }
        });

        b_13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/13S.png"))); // NOI18N
        b_13.setToolTipText("King");
        b_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_addCardsLayout = new javax.swing.GroupLayout(panel_addCards);
        panel_addCards.setLayout(panel_addCardsLayout);
        panel_addCardsLayout.setHorizontalGroup(
            panel_addCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addCardsLayout.createSequentialGroup()
                .addGroup(panel_addCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_addCardsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(b_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_addCardsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_addCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_10))
                        .addGap(18, 18, 18)
                        .addGroup(panel_addCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_7)
                            .addComponent(b_11))
                        .addGap(10, 10, 10)
                        .addGroup(panel_addCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_8)
                            .addComponent(b_12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_addCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_9)
                            .addComponent(b_13))
                        .addGap(18, 18, 18)
                        .addComponent(b_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_addCardsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {b_1, b_10, b_11, b_12, b_13, b_2, b_3, b_4, b_5, b_6, b_7, b_8, b_9});

        panel_addCardsLayout.setVerticalGroup(
            panel_addCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addCardsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_addCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_addCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_addCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_10)
                    .addComponent(b_11)
                    .addComponent(b_12)
                    .addComponent(b_13))
                .addGap(127, 127, 127))
        );

        panel_addCardsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {b_1, b_10, b_11, b_12, b_13, b_2, b_3, b_4, b_5, b_6, b_7, b_8, b_9});

        slider_suit.setMaximum(4);
        slider_suit.setMinimum(1);
        slider_suit.setOrientation(javax.swing.JSlider.VERTICAL);
        slider_suit.setPaintLabels(true);
        slider_suit.setPaintTrack(false);
        slider_suit.setToolTipText("Change Suits");
        Hashtable<Integer, javax.swing.JLabel> labels = new Hashtable<>();
        labels.put(4, new javax.swing.JLabel("Spades"));
        labels.put(3, new javax.swing.JLabel("Hearts"));
        labels.put(2, new javax.swing.JLabel("Clubs"));
        labels.put(1, new javax.swing.JLabel("Diamonds"));
        slider_suit.setLabelTable(labels);
        slider_suit.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_suitStateChanged(evt);
            }
        });

        txt_hand.setEditable(false);
        txt_hand.setColumns(20);
        txt_hand.setLineWrap(true);
        txt_hand.setRows(5);
        txt_hand.setToolTipText("Hand");
        txt_hand.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txt_hand);

        l_hand.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        l_hand.setText("Hand");

        l_addCards.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        l_addCards.setText("ADD CARDS");

        txt_points.setEditable(false);
        txt_points.setColumns(20);
        txt_points.setRows(5);
        txt_points.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txt_points);

        b_calcPoints.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        b_calcPoints.setText("Calculate Points");
        b_calcPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_calcPointsActionPerformed(evt);
            }
        });

        l_points.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        l_points.setText("Points");

        cribT.setText("Player has a Crib");
        cribT.setToolTipText("");
        cribT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cribTActionPerformed(evt);
            }
        });

        cribH.setText("Hand is a Crib");
        cribH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cribHActionPerformed(evt);
            }
        });

        l_cutCard.setText("The first Card Entered Will be the Cut Card");

        b_clearHand.setText("Clear Hand");
        b_clearHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_clearHandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(slider_suit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(panel_addCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_addCards, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_points))
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_calcPoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_hand, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cribT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cribH)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_clearHand))
                    .addComponent(l_cutCard))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(l_addCards, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_addCards, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slider_suit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(l_hand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_cutCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_clearHand))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cribT)
                            .addComponent(cribH))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(b_calcPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(l_points)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //for displaying the textual representation of the card in the hand text field
    private void displayHand(String card){
        switch(global_suit){
            case "Spades":
                txt_hand.setText(txt_hand.getText() + card + "♠, ");
                break;
            case "Hearts":
                txt_hand.setText(txt_hand.getText() + card + "♥, ");
                break;
            case "Clubs":
                txt_hand.setText(txt_hand.getText() + card + "♣, ");
                break;
            case "Diamonds":
                txt_hand.setText(txt_hand.getText() + card + "♦, ");
                break;
        }
    }
        
    
    private void b_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_1ActionPerformed
        //Create new card and add it to the hand
        Card c = new Card(1,1,"Ace",global_suit);
        hand.add(c);
        displayHand("Ace");
    }//GEN-LAST:event_b_1ActionPerformed

    private void b_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_2ActionPerformed
        // TODO add your handling code here:
        Card c = new Card(2,2,"2",global_suit);
        hand.add(c);
        displayHand("2");
    }//GEN-LAST:event_b_2ActionPerformed

    //changes the suit of the addCards buttons
    private void slider_suitStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_suitStateChanged
        // TODO add your handling code here:
        int suit = slider_suit.getValue();
        
        ArrayList<javax.swing.JButton> buttons = new ArrayList<javax.swing.JButton>();
        buttons.add(b_1);
        buttons.add(b_2);
        buttons.add(b_3);
        buttons.add(b_4);
        buttons.add(b_5);
        buttons.add(b_6);
        buttons.add(b_7);
        buttons.add(b_8);
        buttons.add(b_9);
        buttons.add(b_10);
        buttons.add(b_11);
        buttons.add(b_12);
        buttons.add(b_13);
        
        if(suit == 4){
            global_suit = "Spades";
            for(int i =1; i<=buttons.size(); i++){
                buttons.get(i-1).setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/"+ i +"S.png"))); 
            }
        }
        else if(suit == 3){
            global_suit = "Hearts";
            for(int i =1; i<=buttons.size(); i++){
                buttons.get(i-1).setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/"+ i +"H.png"))); 
            }
        }
        else if(suit == 2){
            global_suit = "Clubs";
            for(int i =1; i<=buttons.size(); i++){
                buttons.get(i-1).setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/"+ i +"C.png"))); 
            }
        }
        else{
            global_suit = "Diamonds";
            for(int i =1; i<=buttons.size(); i++){
                buttons.get(i-1).setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/deck/"+ i +"D.png"))); 
            }
        }
        
    }//GEN-LAST:event_slider_suitStateChanged

    private void b_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_6ActionPerformed
        // TODO add your handling code here:
        Card c = new Card(6,6,"6",global_suit);
        hand.add(c);
        displayHand("6");
        
    }//GEN-LAST:event_b_6ActionPerformed

    private void b_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_3ActionPerformed
        // TODO add your handling code here:
        Card c = new Card(3,3,"3",global_suit);
        hand.add(c);
        displayHand("3");
    }//GEN-LAST:event_b_3ActionPerformed

    private void b_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4ActionPerformed
        // TODO add your handling code here:
        Card c = new Card(4,4,"4",global_suit);
        hand.add(c);
        displayHand("4");
    }//GEN-LAST:event_b_4ActionPerformed

    private void b_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_5ActionPerformed
        // TODO add your handling code here:
        Card c = new Card(5,5,"5",global_suit);
        hand.add(c);
        displayHand("5");
    }//GEN-LAST:event_b_5ActionPerformed

    private void b_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_7ActionPerformed
        // TODO add your handling code here:
        Card c = new Card(7,7,"7",global_suit);
        hand.add(c);
        displayHand("7");
    }//GEN-LAST:event_b_7ActionPerformed

    private void b_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_8ActionPerformed
        // TODO add your handling code here:
        Card c = new Card(8,8,"8",global_suit);
        hand.add(c);
        displayHand("8");
    }//GEN-LAST:event_b_8ActionPerformed

    private void b_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_9ActionPerformed
        // TODO add your handling code here:
        Card c = new Card(9,9,"9",global_suit);
        hand.add(c);
        displayHand("9");
    }//GEN-LAST:event_b_9ActionPerformed

    private void b_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_10ActionPerformed
        // TODO add your handling code here:
        Card c = new Card(10,10,"10",global_suit);
        hand.add(c);
        displayHand("10");
    }//GEN-LAST:event_b_10ActionPerformed

    private void b_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_11ActionPerformed
        // TODO add your handling code here:
        Card c = new Card(10,11,"Jack",global_suit);
        hand.add(c);
        displayHand("Jack");
    }//GEN-LAST:event_b_11ActionPerformed

    private void b_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_12ActionPerformed
        // TODO add your handling code here:
       Card c = new Card(10,12,"Queen",global_suit);
        hand.add(c);
        displayHand("Queen");
    }//GEN-LAST:event_b_12ActionPerformed

    private void b_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_13ActionPerformed
        // TODO add your handling code here:
       Card c = new Card(10,13,"King",global_suit);
        hand.add(c);
        displayHand("King");
    }//GEN-LAST:event_b_13ActionPerformed

    private void b_calcPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_calcPointsActionPerformed
        // TODO add your handling code here:
        hand.setCut(hand.get(0));
        CalcCribPoints calc = new CalcCribPoints(hand);
        HashMap<String,Integer> points = calc.getPoints();
        
        String dp = ""; //displayPoints in txt_points
        dp += "Nobs:" + points.get("nob") + "\t";
        dp += "Nibs:" + points.get("nib") + "\n";
        dp += "Flush:" + points.get("suit") + "\t";
        dp += "Pairs:" + points.get("pair") + "\n";
        dp += "Runs:" + points.get("run") + "\t";
        dp += "Fifteens:" + points.get("fifteen") + "\n";
        dp += "Total:" + points.get("total");
        
        txt_points.setText(dp);
        
    }//GEN-LAST:event_b_calcPointsActionPerformed

    private void cribHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cribHActionPerformed
        // TODO add your handling code here:
        //if it is not a cribTurn (starting value)
        if(!hand.getCribH())
            hand.setCribH(true);
        else
            hand.setCribH(false);
    }//GEN-LAST:event_cribHActionPerformed

    private void cribTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cribTActionPerformed
        // TODO add your handling code here:
        if(!hand.getCribT())
            hand.setCribT(true);
        else
            hand.setCribT(false);
    }//GEN-LAST:event_cribTActionPerformed

    private void b_clearHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_clearHandActionPerformed
        // TODO add your handling code here:
        hand.clear();
        hand.setCribH(false);
        hand.setCribT(false);
        hand.setCut(null);
        
        txt_hand.setText("");
    }//GEN-LAST:event_b_clearHandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pointCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pointCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pointCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pointCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pointCalcGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_1;
    private javax.swing.JButton b_10;
    private javax.swing.JButton b_11;
    private javax.swing.JButton b_12;
    private javax.swing.JButton b_13;
    private javax.swing.JButton b_2;
    private javax.swing.JButton b_3;
    private javax.swing.JButton b_4;
    private javax.swing.JButton b_5;
    private javax.swing.JButton b_6;
    private javax.swing.JButton b_7;
    private javax.swing.JButton b_8;
    private javax.swing.JButton b_9;
    private javax.swing.JButton b_calcPoints;
    private javax.swing.JButton b_clearHand;
    private javax.swing.JRadioButton cribH;
    private javax.swing.JRadioButton cribT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l_addCards;
    private javax.swing.JLabel l_cutCard;
    private javax.swing.JLabel l_hand;
    private javax.swing.JLabel l_points;
    private javax.swing.JPanel panel_addCards;
    private javax.swing.JSlider slider_suit;
    private javax.swing.JTextArea txt_hand;
    private javax.swing.JTextArea txt_points;
    // End of variables declaration//GEN-END:variables
}
